### ISSUE TITLE
Add OpenAI inference logic

### ISSUE THREAD

**Issue by kislerdm** [kislerdm/diagramastext#1]
## Problem

User input text has to be converted to the instructions for [PlantUML](https://plantuml.com/) to generate diagram.

## Proposed Solution

Develop `ClientOpenAI` to communicate with OpenAI over HTTP using [the Rest API](https://platform.openai.com/docs/api-reference/):
- The client will configured with the following attributes:
    - `token`
    - `organization`
    - `modelID`
- The http client shall implement a middleware to authenticate with OpenAI, see the [docu](https://platform.openai.com/docs/api-reference/authentication)
- The client's interface will have the method `InferModel(prompt string)` to call the model, see the [contract](https://platform.openai.com/docs/api-reference/completions/create).
- The `InferModel` output will contain the `DiagramGraph` object:
```go
type DiagramGraph struct {
	Title  string
	Footer string
	Nodes  []*Node
	Links  []*Link
}

type Node struct {
	ID         string `json:"id"`
	Label      string `json:"label"`
	Group      string `json:"group"`
	Technology string `json:"technology"`
	External   bool   `json:"external"`
	IsQueue    bool   `json:"is_queue"`
	IsDatabase bool   `json:"is_database"`
}

type Link struct {
	From       string `json:"from"`
	To         string `json:"to"`
	Direction  string `json:"direction"`
	Label      string `json:"label"`
	Technology string `json:"technology"`
}
```

## DoD

- The logic is implemented in the `openai.go`
- Test coverage is at least `80%`

**Comment by ColeDrain** [comment]
discussion: @kislerdm what do you think about getting the DiagramGraph object, should the Plant UML response model from OpenAI be parsed to create the object or should OpenAI generate the DuagramGraph object, which do you think is more feasible?

**Comment by kislerdm** [comment]
@ColeDrain Hey Ugo, thanks for the question. It is expected that OpenAI client returns the object of the `DiagramGraph` type because it’s data struct defining internal API of our module. All operations are performed around the graph defining diagram - it’d be vertical reasonable to set the graph type as the the logic API. WDYT?

**Comment by kislerdm** [comment]
@ColeDrain btw I'd like to propose adjustment to the task definition if you don't mind. `ClientOpenAI` shall implemented the method `Do` to following the signatures of the interface:

```go
// ClientInputToGraph client to convert user input inquiry to the DiagramGraph.
type ClientInputToGraph interface {
	Do(string) (DiagramGraph, error)
}
```

I made the proposal [here](https://github.com/kislerdm/diagramastext/blob/feat/graph-to-plantuml/core/core.go). WDYT?

**Comment by kislerdm** [comment]
@ColeDrain please consult with the references mentioned in #12 - we go live w/o model fine-tuning. Thanks!
