### ISSUE TITLE
Fix the downloadable SVG file of a diagram

### ISSUE THREAD

**Issue by zotttttttt** [kislerdm/diagramastext#28]
## Environment
- App version: 39aa2443fce8188aa6f7713ce20e3f9e2a7ca046

## Prompt

```
the banking application that supports not only a mobile app, but also a single-page application. We also have an e-mail system and it's all supported via our Bank API that is connected to the database (we use Oracle)
```

## Details

1. Copy/paste a prompt
2. Click "Generate a diagram"
3. Diagramastext displays a diagram
4. Click "Download"
5. Open a `diagram.svg` file in a browser
6. See it being broken, with no diagram's elements

![diagram.svg](https://user-images.githubusercontent.com/5555607/218350247-cdd7ab83-9831-4f95-a8bc-e553d2da4c6c.svg) contains this:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" contentStyleType="text/css" height="458px" preserveAspectRatio="none" style="width:352px;height:458px;background:
```

## Expected behaviour

6. The downloaded SVG file is filled with the diagram's elements and can be opened in the browser to display an actual diagram

**Comment by kislerdm** [comment]
@zotttttttt hey! could you please double check if the issue was resolved. thanks!

**Comment by zotttttttt** [comment]
> @zotttttttt hey! could you please double check if the issue was resolved. thanks!

All good now. Thanks! 👍
